name: mask3d_cuda113
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - boltons=23.0.0=py310h06a4308_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.3.1=py310h06a4308_0
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=2.0.2=py310h06a4308_0
  - conda-package-streaming=0.7.0=py310h06a4308_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - idna=3.4=py310h06a4308_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.21=h043d6bf_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nomkl=3.0=0
  - openblas-devel=0.3.21=h06a4308_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_1
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - setuptools=65.6.3=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - tqdm=4.65.0=py310h2f386ee_0
  - urllib3=1.26.15=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py310h5eee18b_0
  - pip
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==1.2.1
      - antlr4-python3-runtime==4.8
      - anyio==3.6.2
      - appdirs==1.4.4
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - backcall==0.2.0
      - black==21.4b2
      - cachetools==5.3.0
      - click==8.1.3
      - cloudpickle==2.1.0
      - comm==0.1.3
      - configargparse==1.5.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dash==2.9.3
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.7
      - decorator==5.1.1
      # - detectron2==0.6
      - docker-pycreds==0.4.0
      - executing==1.2.0
      - fastapi==0.95.1
      - fastjsonschema==2.16.3
      - fire==0.4.0
      - flake8==6.0.0
      - flask==2.2.3
      - fonttools==4.39.3
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - fvcore==0.1.5.post20220512
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - h11==0.14.0
      - hydra-core==1.0.5
      - imageio==2.21.1
      - importlib-metadata==3.10.1
      - iopath==0.1.10
      - ipykernel==6.22.0
      - ipython==8.12.0
      - ipywidgets==8.0.6
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - loguru==0.6.0
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      # - minkowskiengine==0.5.4
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - natsort==8.3.1
      - nbformat==5.7.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - ninja==1.10.2.3
      - numpy==1.24.2
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - open3d==0.17.0
      - opencv-python-headless==4.7.0.72
      - pandas==2.0.0
      - parso==0.8.3
      - pathspec==0.11.1
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==23.1
      - platformdirs==3.2.0
      - plotly==5.14.1
      - plyfile==0.7.4
      # - pointnet2==0.0.0
      - portalocker==2.7.0
      - prompt-toolkit==3.0.38
      - protobuf==4.22.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.4
      - pydantic==1.10.7
      - pydeprecate==0.3.2
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-dotenv==0.20.0
      - python-multipart==0.0.6
      # - pytorch-lightning==1.7.2
      - pytz==2023.3
      - pyviz3d==0.2.28
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - pyzmq==25.0.2
      - qudida==0.0.4
      - regex==2023.3.23
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.20.0
      - scikit-learn==1.1.2
      - scipy==1.9.0
      - sentry-sdk==1.20.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - stack-data==0.6.2
      - starlette==0.26.1
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - toml==0.10.2
      # - torch==1.12.1+cu113
      # - torch-scatter==2.1.1
      # - torchmetrics==0.11.4
      # - torchvision==0.13.1+cu113
      - tornado==6.3
      - traitlets==5.9.0
      - trimesh==3.14.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - uvicorn==0.21.1
      - volumentations==0.1.8
      - wandb==0.15.0
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.7
      - yacs==0.1.8
      - yarl==1.8.2
      - zipp==3.15.0
prefix: /opt/conda
